pipeline {
  agent any

  stages {
    stage('Unit Tests') {
      steps {
        sh 'ant -f test.xml -v'
        junit 'reports/result.xml'
      } 
    }
    stage('build') {
      steps {
        sh 'ant -f jenkins/exercises/java-project/build.xml -v'
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'jenkins/exercises/java-project/dist/*.jar', fingerprint: true
    }
  }
}
