pipeline {
  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '2', artifactNumToKeepStr: '1'))
  }
  stages {
    stage('build') {
      steps {
        sh 'ant -f jenkins/exercises/java-project/build.xml -v'
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'jenkins/exercises/java-project/dist/*.jar', fingerprint: true
    }
  }
}
